apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: cattle-system
  annotations:
    cert-manager.io/issuer: "selfsigned-issuer"
    # Traefik: backend HTTPS konusur (rancher 443) + websecure entrypoint
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - rancher.homelab.local
    secretName: rancher-homelab-tls
  rules:
  - host: rancher.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rancher
            port:
              number: 443

