# grafana-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: grafana
spec:
  secretName: grafana-tls
  duration: 8760h
  renewBefore: 2160h
  commonName: grafana.foxhound.com.tr
  dnsNames:
  - grafana.foxhound.com.tr
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
