---
# Check Longhorn disk usage and node status
- hosts: master
  become: true
  vars_files:
    - playbooks/roles/k3s_setup/vars/main.yml
  tasks:
    - name: Find home directory for UID 1000
      command: getent passwd 1000
      register: getent_passwd_output
      changed_when: false
      when: inventory_hostname == groups['master'][0]

    - name: Set home directory variable
      set_fact:
        user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
      when:
        - inventory_hostname == groups['master'][0]
        - getent_passwd_output.stdout != ""

    - name: Define the user name with UID 1000
      command: getent passwd 1000
      register: getent_passwd_result
      changed_when: false
      when: inventory_hostname == groups['master'][0]

    - name: Set user name variable from getent passwd output
      set_fact:
        uid_1000_user: "{{ getent_passwd_result.stdout.split(':')[0] }}"
      when:
        - inventory_hostname == groups['master'][0]
        - getent_passwd_result.stdout != ''

    - name: Check actual disk usage on worker nodes
      ansible.builtin.shell:
        cmd: |
          echo "=== Worker Node Disk Usage ==="
          for node in worker-2 worker-3; do
            echo ""
            echo "Node: $node"
            kubectl get nodes $node -o jsonpath='{.status.capacity.storage}' 2>/dev/null || echo "N/A"
            echo ""
            echo "Longhorn disk path usage:"
            ssh -o StrictHostKeyChecking=no $node "df -h /var/lib/longhorn/ 2>/dev/null || echo 'Path not found'" || echo "SSH failed"
          done
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: disk_usage_check
      changed_when: false

    - name: Display disk usage
      ansible.builtin.debug:
        msg: "{{ disk_usage_check.stdout }}"
      when:
        - inventory_hostname == groups['master'][0]
        - disk_usage_check.stdout is defined

    - name: Check Longhorn node status
      ansible.builtin.command:
        cmd: kubectl get nodes -o wide
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: node_status
      changed_when: false

    - name: Display node status
      ansible.builtin.debug:
        msg: "{{ node_status.stdout_lines }}"
      when:
        - inventory_hostname == groups['master'][0]
        - node_status.stdout is defined

    - name: Check Longhorn volumes
      ansible.builtin.command:
        cmd: kubectl get volumes -n longhorn-system -o wide
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: volumes_status
      changed_when: false

    - name: Display volumes status
      ansible.builtin.debug:
        msg: "{{ volumes_status.stdout_lines }}"
      when:
        - inventory_hostname == groups['master'][0]
        - volumes_status.stdout is defined

    - name: Check Longhorn node disk allocation (using Longhorn CRD)
      ansible.builtin.shell:
        cmd: kubectl get nodes.longhorn.io -n longhorn-system -o json | jq -r '.items[] | "\(.metadata.name) Allocated=\(.status.allocated // "N/A") Capacity=\(.status.capacity // "N/A") StorageReserved=\(.status.storageReserved // "N/A")"'
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: longhorn_node_disk
      changed_when: false
      failed_when: false

    - name: Display Longhorn node disk allocation
      ansible.builtin.debug:
        msg: "{{ longhorn_node_disk.stdout_lines }}"
      when:
        - inventory_hostname == groups['master'][0]
        - longhorn_node_disk.stdout is defined
        - longhorn_node_disk.stdout != ""

    - name: Check Longhorn disk usage summary
      ansible.builtin.shell:
        cmd: |
          echo "=== Longhorn Disk Usage Summary ==="
          echo ""
          echo "Volumes (with replica info):"
          kubectl get volumes -n longhorn-system -o json | jq -r '.items[] | "\(.metadata.name) Size=\(.spec.size) State=\(.status.state) Node=\(.status.currentNodeID // "N/A") Replicas=\(.status.replicas | length)"'
          echo ""
          echo "Longhorn Nodes (CRD):"
          kubectl get nodes.longhorn.io -n longhorn-system -o wide 2>/dev/null || echo "Longhorn nodes CRD not found, trying alternative..."
          echo ""
          echo "Longhorn Node Details (JSON):"
          kubectl get nodes.longhorn.io -n longhorn-system -o json 2>/dev/null | jq -r '.items[]? | "\(.metadata.name) Allocated=\(.status.allocated // "N/A") Capacity=\(.status.capacity // "N/A") StorageReserved=\(.status.storageReserved // "N/A")"' || echo "No Longhorn nodes found"
          echo ""
          echo "PVC Summary:"
          kubectl get pvc -A -o json | jq -r '.items[] | "\(.metadata.namespace)/\(.metadata.name) Size=\(.spec.resources.requests.storage) StorageClass=\(.spec.storageClassName)"'
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: longhorn_summary
      changed_when: false
      failed_when: false

    - name: Display Longhorn disk usage summary
      ansible.builtin.debug:
        msg: "{{ longhorn_summary.stdout_lines }}"
      when:
        - inventory_hostname == groups['master'][0]
        - longhorn_summary.stdout is defined
        - longhorn_summary.stdout != ""

