---
# Rebalance pods across nodes to utilize new worker nodes
# This playbook drains and uncordons nodes to force pod redistribution

- hosts: master
  become: true
  vars_files:
    - playbooks/roles/k3s_setup/vars/main.yml
  tasks:
    - name: Find home directory for UID 1000
      command: getent passwd 1000
      register: getent_passwd_output
      changed_when: false
      when: inventory_hostname == groups['master'][0]

    - name: Set home directory variable
      set_fact:
        user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
      when: 
        - inventory_hostname == groups['master'][0]
        - getent_passwd_output.stdout != ""

    - name: Define the user name with UID 1000
      command: getent passwd 1000
      register: getent_passwd_result
      changed_when: false
      when: inventory_hostname == groups['master'][0]

    - name: Set user name variable from getent passwd output
      set_fact:
        uid_1000_user: "{{ getent_passwd_result.stdout.split(':')[0] }}"
      when: 
        - inventory_hostname == groups['master'][0]
        - getent_passwd_result.stdout != ''

    - name: Display current pod distribution
      ansible.builtin.shell:
        cmd: kubectl get pods --all-namespaces -o wide --no-headers | awk '{print $8}' | sort | uniq -c | sort -rn
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: current_pod_distribution
      changed_when: false

    - name: Show current pod distribution
      ansible.builtin.debug:
        msg: |
          Current Pod Distribution:
          {{ current_pod_distribution.stdout_lines | default(['No pods found']) | join('\n') }}
      when: inventory_hostname == groups['master'][0]

    - name: Get list of worker nodes with high pod count
      ansible.builtin.shell:
        cmd: |
          kubectl get pods --all-namespaces -o wide --no-headers | \
          awk '{print $8}' | sort | uniq -c | \
          awk '$1 > 3 && $2 ~ /^worker/ {print $2}' | sort
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: overloaded_workers
      changed_when: false
      failed_when: false

    - name: Display overloaded workers
      ansible.builtin.debug:
        msg: |
          Workers with high pod count (will be drained to rebalance):
          {{ overloaded_workers.stdout_lines | default(['None']) | join('\n') }}
      when: 
        - inventory_hostname == groups['master'][0]
        - overloaded_workers.stdout is defined
        - overloaded_workers.stdout != ""

    - name: Drain and uncordon overloaded workers to rebalance pods
      block:
        - name: Drain worker node for rebalancing
          ansible.builtin.command:
            cmd: kubectl drain {{ item }} --ignore-daemonsets --delete-emptydir-data --timeout=300s --grace-period=60 --force
          become: true
          become_user: "{{ uid_1000_user }}"
          environment:
            KUBECONFIG: "{{ user_home_directory }}/.kube/config"
          when: 
            - inventory_hostname == groups['master'][0]
            - overloaded_workers.stdout is defined
            - overloaded_workers.stdout != ""
            - item | trim != ""
          delegate_to: "{{ groups['master'][0] }}"
          loop: "{{ overloaded_workers.stdout_lines | default([]) }}"
          register: drain_results
          failed_when: false

        - name: Wait for pods to be rescheduled
          ansible.builtin.pause:
            seconds: 30
          when: inventory_hostname == groups['master'][0]

        - name: Uncordon worker nodes
          ansible.builtin.command:
            cmd: kubectl uncordon {{ item.item }}
          become: true
          become_user: "{{ uid_1000_user }}"
          environment:
            KUBECONFIG: "{{ user_home_directory }}/.kube/config"
          when: 
            - inventory_hostname == groups['master'][0]
            - overloaded_workers.stdout is defined
            - overloaded_workers.stdout != ""
            - item.item | trim != ""
          delegate_to: "{{ groups['master'][0] }}"
          loop: "{{ drain_results.results | default([]) }}"
          register: uncordon_results
          failed_when: false

        - name: Wait for pods to stabilize after rebalancing
          ansible.builtin.pause:
            seconds: 30
          when: inventory_hostname == groups['master'][0]

      when: 
        - inventory_hostname == groups['master'][0]
        - overloaded_workers.stdout is defined
        - overloaded_workers.stdout != ""

    - name: Display final pod distribution
      ansible.builtin.shell:
        cmd: kubectl get pods --all-namespaces -o wide --no-headers | awk '{print $8}' | sort | uniq -c | sort -rn
      become: true
      become_user: "{{ uid_1000_user }}"
      environment:
        KUBECONFIG: "{{ user_home_directory }}/.kube/config"
      when: inventory_hostname == groups['master'][0]
      delegate_to: "{{ groups['master'][0] }}"
      register: final_pod_distribution
      changed_when: false

    - name: Show final pod distribution
      ansible.builtin.debug:
        msg: |
          Final Pod Distribution (after rebalancing):
          {{ final_pod_distribution.stdout_lines | default(['No pods found']) | join('\n') }}
      when: inventory_hostname == groups['master'][0]

