all:
  children:
    master:
      hosts:
        master-1:
          ansible_host: 192.168.2.245
        # master-2:
        #   ansible_host: 192.168.2.222
        # master-3:
        #   ansible_host: 192.168.2.223
    worker:
      hosts:
        worker-1:
          ansible_host: 192.168.2.246
        worker-2:
          ansible_host: 192.168.2.247
        # worker-3:
        #   ansible_host: 192.168.2.233
