all:
  children:
    master:
      hosts:
        master-1:
          ansible_host: 192.168.1.152
        master-2:
          ansible_host: 192.168.1.153
        master-3:
          ansible_host: 192.168.1.156
    # worker:
    #   hosts:
    #     worker-1:
    #       ansible_host: 192.168.1.94
    #     # worker-2:
    #     #   ansible_host: 192.168.1.156
    #     # worker-3:
    #     #   ansible_host: 192.168.1.157
