apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-longhorn-cert
  namespace: longhorn-system
spec:
  secretName: homelab-longhorn-tls
  duration: 8760h
  renewBefore: 2160h
  commonName: longhorn.foxhound.com.tr
  dnsNames:
  - longhorn.foxhound.com.tr
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
