apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-longhorn-cert
  namespace: longhorn-system
spec:
  secretName: homelab-longhorn-tls
  duration: 24h
  renewBefore: 12h
  commonName: homelab.longhorn
  dnsNames:
  - homelab.longhorn
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer

