# grafana-values.yaml
replicaCount: 2

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500Mi

persistence:
  enabled: true
  storageClassName: longhorn-retain-1
  accessModes:
    - ReadWriteOnce
  size: 10Gi

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - grafana
        topologyKey: "kubernetes.io/hostname"