# prometheus-values.yaml
server:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistentVolume:
    enabled: true
    storageClass: longhorn-retain-1
    size: 10Gi

alertmanager:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 500Mi
  persistentVolume:
    enabled: true
    storageClass: longhorn-retain-1
    size: 2Gi
