replicas: 3
minimumMasterNodes: 2
esJavaOpts: "-Xmx1g -Xms1g"
persistence:
  enabled: true
  storageClass: longhorn-retain-1
  size: 30Gi
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"