---
# ============================
# Install Nginx Ingress
# ============================

- name: Check if ingress-nginx namespace exists
  command: kubectl get namespace ingress-nginx
  register: namespace_exists
  failed_when: false
  changed_when: false
  when: "'master' in group_names"

- name: Check if NGINX Ingress Helm repository is already added
  ansible.builtin.command:
    cmd: helm repo list
  register: helm_repo_list
  ignore_errors: true
  become: true
  become_user: "{{ uid_1000_user }}"
  when: "'master' in group_names"

- name: Fail if helm repo list failed for reasons other than no repositories
  ansible.builtin.fail:
    msg: "Failed to list Helm repositories: {{ helm_repo_list.stderr }}"
  when: 
    - "'master' in group_names"
    - helm_repo_list.rc != 0
    - "'Error: no repositories to show' not in helm_repo_list.stderr"

- name: Extract Helm repository names
  ansible.builtin.shell: |
    echo "{{ helm_repo_list.stdout }}" | awk 'NR > 1 {print $1}'
  register: helm_repo_names
  when: "'master' in group_names"

- name: Check if NGINX Ingress Helm repository is already present
  ansible.builtin.set_fact:
    nginx_ingress_repo_present: "{{ 'ingress-nginx' in helm_repo_names.stdout }}"
  when: "'master' in group_names"

- name: Debug if NGINX Ingress Helm repository is present
  ansible.builtin.debug:
    msg: "NGINX Ingress Helm repository is present: {{ nginx_ingress_repo_present }}"
  when: "'master' in group_names"

- name: Add NGINX Ingress Helm repository
  ansible.builtin.command:
    cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  become: true
  become_user: "{{ uid_1000_user }}"
  when: 
    - "'master' in group_names"
    - not nginx_ingress_repo_present

- name: Debug message if NGINX Ingress Helm repository is already present
  ansible.builtin.debug:
    msg: "NGINX Ingress Helm repository is already added."
  when:
    - "'master' in group_names"
    - nginx_ingress_repo_present

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  become: true
  become_user: "{{ uid_1000_user }}"
  when: 
    - "'master' in group_names"

- name: Install NGINX Ingress Helm chart
  ansible.builtin.command:
    cmd: helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace -f {{ user_home_directory }}/my-charts/ingress/values.yaml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0

- name: Wait for Ingress pods to be in Running state
  command: kubectl get pods -n ingress-nginx -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[*].status.phase}'
  register: ingress_pod_status
  until: ingress_pod_status.stdout.find('Running') != -1
  retries: 10
  delay: 60
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0
