# Steps to install NGINX Ingress
---

- name: Check if ingress-nginx namespace exists
  command: kubectl get namespace ingress-nginx
  register: namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add NGINX Ingress Helm repository
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0

- name: Install NGINX Ingress Helm chart
  ansible.builtin.command:
    cmd: helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace -f {{ user_home_directory }}/my-charts/ingress/values.yaml
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0

- name: Wait for Ingress pods to be in Running state
  command: kubectl get pods -n ingress-nginx -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[*].status.phase}'
  register: ingress_pod_status
  until: ingress_pod_status.stdout.find('Running') != -1
  retries: 10
  delay: 30
  when: 
    - inventory_hostname == 'master-1'
    - namespace_exists.rc != 0
