# Steps to install MetalLB
---

- name: Check if metallb-system namespace exists
  command: kubectl get namespace metallb-system
  register: metallb_namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add MetalLB Helm repository
  community.kubernetes.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  when: 
    - inventory_hostname == 'master-1'
    - metallb_namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - metallb_namespace_exists.rc != 0

- name: Install MetalLB using Helm
  ansible.builtin.command:
    cmd: helm install metallb metallb/metallb --namespace metallb-system --create-namespace
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - metallb_namespace_exists.rc != 0

- name: Wait for MetalLB pods to be in Running state
  command: kubectl get pods -n metallb-system -l app=metallb -o jsonpath='{.items[*].status.phase}'
  register: metallb_pod_status
  until: metallb_pod_status.stdout.find('Running') != -1
  retries: 10
  delay: 30
  when: inventory_hostname == 'master-1'

- name: Apply MetalLB ConfigMap
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb-config.yaml
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: inventory_hostname == 'master-1'
