---
# ============================
# Install MetalLB
# ============================

- name: Check if metallb-system namespace exists
  command: kubectl get namespace metallb-system
  register: metallb_namespace_exists
  failed_when: false
  changed_when: false
  when: "'master' in group_names"

- name: Check if MetalLB Helm repository is already added
  ansible.builtin.command:
    cmd: helm repo list
  register: helm_repo_list
  ignore_errors: true
  become: true
  become_user: "{{ uid_1000_user }}"
  when: "'master' in group_names"

- name: Fail if helm repo list failed for reasons other than no repositories
  ansible.builtin.fail:
    msg: "Failed to list Helm repositories: {{ helm_repo_list.stderr }}"
  when: 
    - "'master' in group_names"
    - helm_repo_list.rc != 0
    - "'Error: no repositories to show' not in helm_repo_list.stderr"

- name: Extract Helm repository names
  ansible.builtin.shell: |
    echo "{{ helm_repo_list.stdout }}" | awk 'NR > 1 {print $1}'
  register: helm_repo_names
  when: "'master' in group_names"

- name: Check if MetalLB Helm repository is already present
  ansible.builtin.set_fact:
    metallb_repo_present: "{{ 'metallb' in helm_repo_names.stdout }}"
  when: "'master' in group_names"

- name: Debug if MetalLB Helm repository is present
  ansible.builtin.debug:
    msg: "MetalLB Helm repository is present: {{ metallb_repo_present }}"
  when: "'master' in group_names"

- name: Add MetalLB Helm repository
  ansible.builtin.command:
    cmd: helm repo add metallb https://metallb.github.io/metallb
  become: true
  become_user: "{{ uid_1000_user }}"
  when: 
    - "'master' in group_names"
    - not metallb_repo_present

- name: Debug message if MetalLB Helm repository is already present
  ansible.builtin.debug:
    msg: "MetalLB Helm repository is already added."
  when:
    - "'master' in group_names"
    - metallb_repo_present

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  become: true
  become_user: "{{ uid_1000_user }}"
  when: 
    - "'master' in group_names"

- name: Install MetalLB using Helm
  ansible.builtin.command:
    cmd: helm install metallb metallb/metallb --namespace metallb-system --create-namespace
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - metallb_namespace_exists.rc != 0

- name: Wait for MetalLB pods to be in Running state
  shell: |
    kubectl get pods -n metallb-system -o jsonpath='{.items[*].status.phase}' | grep -v Running && exit 1 || exit 0
  register: result
  until: result.rc == 0
  retries: 10
  delay: 60
  when: inventory_hostname == 'master-1'

- name: Apply MetalLB ConfigMap
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb-config.yaml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: inventory_hostname == 'master-1'
