# Steps to install Cert-Manager
---

- name: Check if cert-manager namespace exists
  command: kubectl get namespace cert-manager
  register: cert_manager_namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add Jetstack Helm repository
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    become_user: "{{ uid_1000_user }}"
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
    become_user: "{{ uid_1000_user }}"
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Install Cert-Manager Helm chart
  ansible.builtin.command:
    cmd: helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.13.1 --set installCRDs=true -f {{ user_home_directory }}/my-charts/ingress/values.yaml
    become_user: "{{ uid_1000_user }}"  
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Wait for Cert-Manager pods to be in Running state
  command: kubectl get pods -n cert-manager -l app.kubernetes.io/name=cert-manager -o jsonpath='{.items[*].status.phase}'
  register: cert_manager_pod_status
  until: cert_manager_pod_status.stdout.find('Running') != -1
  retries: 10
  delay: 60
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Apply selfsigned issuer
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/cert-manager/selfsigned-issuer.yaml
    become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"  
  when: 
    - inventory_hostname == 'master-1'