# Steps to install Cert-Manager
---

- name: Check if cert-manager namespace exists
  command: kubectl get namespace cert-manager
  register: cert_manager_namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add Jetstack Helm repository
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Install Cert-Manager Helm chart
  ansible.builtin.command:
    cmd: helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.13.1 --set installCRDs=true -f {{ user_home_directory }}/my-charts/ingress/values.yaml
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0

- name: Pause for 30 seconds to allow Cert-Manager pods to start
  ansible.builtin.pause:
    seconds: 30
  when: 
    - inventory_hostname == 'master-1'
    - cert_manager_namespace_exists.rc != 0
