# Steps to install Longhorn
---

- name: Check if longhorn-system namespace exists
  command: kubectl get namespace longhorn-system
  register: longhorn_namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add Longhorn Helm repository
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f {{ user_home_directory }}/my-charts/longhorn/values.yaml
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Wait for Longhorn pods to be in Running state
  command: kubectl get pods -n longhorn-system -l app=longhorn-manager -o jsonpath='{.items[*].status.phase}'
  register: longhorn_pod_status
  until: longhorn_pod_status.stdout.find('Running') != -1
  retries: 10
  delay: 30
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Longhorn StorageClass
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/storageclass.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Longhorn ingress config
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/homelab.longhorn.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0
    - cert_manager_install | default(false)

- name: Apply homelab.longhorn certificate
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/cert/homelab-longhorn-certificate.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0
    - cert_manager_install | default(false)
