- name: Check if longhorn-system namespace exists
  command: kubectl get namespace longhorn-system
  register: longhorn_namespace_exists
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'master-1'

- name: Add Longhorn Helm repository
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f {{ user_home_directory }}/my-charts/longhorn/values.yaml
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Longhorn ingress config
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/homelab.longhorn.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Apply selfsigned issuer
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/cert/selfsigned-issuer.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Apply homelab longhorn certificate
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/cert/homelab-longhorn-certificate.yaml
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0

- name: Pause for 60 seconds to allow Longhorn pods to start
  ansible.builtin.pause:
    seconds: 60
  when: 
    - inventory_hostname == 'master-1'
    - longhorn_namespace_exists.rc != 0
