

- name: "Install Helm" 
  ansible.builtin.import_tasks: 04_install_helm.yml
  when: helm_install | default(false)

- name: "Install ingress-nginx" 
  ansible.builtin.import_tasks: 05_ingress_install.yaml
  when: ingress_install | default(false)

- name: "Install Metallb" 
  ansible.builtin.import_tasks: 06_metallb_install.yaml
  when: metallb_install | default(false)

- name: "Install Cert-Manager" 
  ansible.builtin.import_tasks: 07_cert_manager_install.yaml
  when: cert_manager_install | default(false)

- name: "Install Longhorn" 
  ansible.builtin.import_tasks: 08_longhorn_install.yaml
  when: longhorn_install | default(false)

- name: "Install Grafana" 
  ansible.builtin.import_tasks: 09_grafana_install.yaml
  when: grafana_install| default(false)