# Main tasks for RKE2 setup
---
- name: "System requirements Check" 
  ansible.builtin.import_tasks: 00_system_requirements.yml

- name: "Configure Hostname"
  ansible.builtin.import_tasks: 01_configure_hostname.yml

- name: "Install and Configure keepalived"
  ansible.builtin.import_tasks: 02_install_keepalived.yml

- name: "Install k3s" 
  ansible.builtin.import_tasks: install_k3s.yml

- name: "Wellcome Message" 
  ansible.builtin.import_tasks: 00_wellcome.yml