apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain-1
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain-2
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain-3
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "3"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-delete-1
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-delete-2
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-delete-3
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "3"